spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: jack
    password: jack@2019
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000         # 客户端等待连接池连接的最大毫秒数
      minimum-idle: 5                    # 最小空闲连接数
      maximum-pool-size: 12             # 配置最大池大小
      idle-timeout: 300000               #允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000              #池中连接关闭后的最长生命周期（以毫秒为单位）
      auto-commit: true                  #从池返回的连接的默认自动提交行为。默认值为true
  session:
    store-type: redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 106.12.145.135
    port: 6379
    password: redis@2019
    timeout: 20s
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 3000ms # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 20 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

server:
  port: 8188
  servlet:
    context-path: /sso

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  config-location: classpath:com/jackinjava/blog/mybatis-config.xml
#  mapper-locations: classpath:com/jackinjava/blog/mapper/*.xml


logging:
  config: classpath:logback-spring.xml
